[env.production]
name = "mcp-guardian-enterprise"
compatibility_date = "2025-08-13"

[env.production.assets]
directory = "."
exclude = ["node_modules", ".git", "*.md", "wrangler.toml", "live_server.js", "server.js", "start.js"]

[[env.production.assets.bindings]]
name = "ASSETS"
