name = "mcp-guardian-enterprise"
compatibility_date = "2025-08-13"

[assets]
directory = "."
exclude = [".git", ".qodo", "node_modules", "DEPLOY.md", "README.md", "wrangler.toml", "live_server.js", "server.js", "start.js"]
